version: 2
jobs:
  build:
    working_directory: ~/the-real-devops-challenge
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Pakcage install
          command: | 
            pip install tox
      - run:
          name: Test with tox
          command: tox

